### ISSUE TITLE
Redirect comment URLs

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/globalredirect#11]
If you have a comment on a node, the link to the comment (e.g. `/comment/1`) simply displays the node page (i.e. it's an alias for `/node/1`). We should redirect those too to prevent duplicate content.

**Comment by quicksketch** [comment]
Thanks @BWPanda. This was added to the 1.6 version of the Drupal module and I ported that patch to Backdrop in https://github.com/backdrop-contrib/globalredirect/issues/19. This feature is now in the Backdrop 1.6.0 version of the module.
