### ISSUE TITLE
Co-maintainership Request

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/globalredirect#12]
Hi @docwilmot, could I help get some fixes out for this module? I'll file a PR with a request to maintainer.

I'm looking to apply the currently open PR that would help a lot, plus I think we could provide an upgrade path from Drupal 7, right now I think all settings are lost.

**Comment by docwilmot** [comment]
Oh wow, didn't even remember porting this. Sadly I dont have merge permissions though. I'd be happy for anyone to merge your PR whenever. Thanks.

**Comment by quicksketch** [comment]
Well that's silly. Must have been a while ago. I think that the general "contrib" group was downgraded from full permissions to Triage level only, but individual maintainers were still supposed to be added to each project. I put your access back as an admin.
