### ISSUE TITLE
Config page mentions "Backdrop 7"

### ISSUE THREAD

**Issue by sutibun** [backdrop-contrib/globalredirect#2]
In the config page ("admin/config/system/globalredirect") there is a minor typo:

![backdropseven](https://cloud.githubusercontent.com/assets/14132746/10271113/aa93ee06-6acb-11e5-81f0-45d4dca51515.png)

> By default this feature is disabled to avoid any unexpected behavior. Also of note, the trailing /0 "depth modifier" was removed from **Backdrop 7.**

Obviously a search & replace of "Drupal" to Backdrop". Not sure what to do about it, if anything, (maybe replace with "earlier versions"?) but bringing it to your attention just in case.

**Comment by ghost** [comment]
Also, the last 'Redirections' dot point in the README mentions 'Backdrop 5'...

**Comment by laryn** [comment]
That whole feature can probably be stripped out if the `/0` behaviour was stripped out in Drupal 7, right?

**Comment by quicksketch** [comment]
Yeah I think @laryn has a good point. I don't see why this setting should still exist when it no longer does anything. Seems like it carried over from Drupal 6 and was just left in place.

**Comment by quicksketch** [comment]
Thanks folks. Fixed in https://github.com/backdrop-contrib/globalredirect/pull/18.
