### ISSUE TITLE
[UX] Settings form save button should have class 'button-primary'

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/globalredirect#5]
<img width="1410" alt="screen shot 2019-02-04 at 11 50 47 am" src="https://user-images.githubusercontent.com/397895/52233120-1e869f80-2873-11e9-8f5b-bb17791600d9.png">

If the buttons are placed into an "actions" element and `system_settings_form(` is called, the classes will be added automatically. 

If not, the `button-primary` class should be added to the save button.

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop-contrib/globalredirect/pull/17. Thanks for reporting!
